// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     http://ubllarsen.codeplex.com/
//
// </auto-generated>
//------------------------------------------------------------------------------
namespace UblLarsen.Ubl2
{
    using UblLarsen.Ubl2.Cac;
    
    
    /// <summary>
    ///  A document that describes the Certificate of Origin.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("ublxsd", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CertificateOfOrigin-2")]
    [System.Xml.Serialization.XmlRootAttribute("CertificateOfOrigin", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CertificateOfOrigin-2", IsNullable=false)]
    public partial class CertificateOfOriginType : UblBaseDocumentType
    {
        
        private Udt.IdentifierType idField;
        
        private Udt.IdentifierType uUIDField;
        
        private Udt.DateType issueDateField;
        
        private Udt.TimeType issueTimeField;
        
        private Udt.TextType[] descriptionField;
        
        private Udt.TextType[] noteField;
        
        private Udt.IdentifierType versionIDField;
        
        private PartyType exporterPartyField;
        
        private PartyType importerPartyField;
        
        private EndorserPartyType[] endorserPartyField;
        
        private CertificateOfOriginApplicationType certificateOfOriginApplicationField;
        
        private EndorsementType issuerEndorsementField;
        
        private EndorsementType embassyEndorsementField;
        
        private EndorsementType insuranceEndorsementField;
        
        /// <summary>
        ///  Unique Identifier of the Certificate Of Origin.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.IdentifierType ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <summary>
        ///  A universally unique identifier for an instance of this ABIE.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.IdentifierType UUID
        {
            get
            {
                return this.uUIDField;
            }
            set
            {
                this.uUIDField = value;
            }
        }
        
        /// <summary>
        ///  Date on which the Certificate Of Origin was issued.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.DateType IssueDate
        {
            get
            {
                return this.issueDateField;
            }
            set
            {
                this.issueDateField = value;
            }
        }
        
        /// <summary>
        ///  Time at which the Certificate Of Origin was issued.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.TimeType IssueTime
        {
            get
            {
                return this.issueTimeField;
            }
            set
            {
                this.issueTimeField = value;
            }
        }
        
        /// <summary>
        ///  Textual description of the document instance.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Description", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.TextType[] Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <summary>
        ///  Textual note associated with a Certificate Of Origin.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Note", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.TextType[] Note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }
        
        /// <summary>
        ///  Version identifier of a Certificate Of Origin.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.IdentifierType VersionID
        {
            get
            {
                return this.versionIDField;
            }
            set
            {
                this.versionIDField = value;
            }
        }
        
        /// <summary>
        ///  The party who makes the export declaration, or on whose behalf the export declaration is made, and who is the owner of the goods or has similar right of disposal over them at the time when the declaration is accepted.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public PartyType ExporterParty
        {
            get
            {
                return this.exporterPartyField;
            }
            set
            {
                this.exporterPartyField = value;
            }
        }
        
        /// <summary>
        ///  The party who makes an import declaration, or on whose behalf a Customs clearing agent or other authorized person makes an import declaration. This may include a person who has possession of the goods or to whom the goods are consigned.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public PartyType ImporterParty
        {
            get
            {
                return this.importerPartyField;
            }
            set
            {
                this.importerPartyField = value;
            }
        }
        
        /// <summary>
        ///  The party providing the endorsement.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("EndorserParty", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public EndorserPartyType[] EndorserParty
        {
            get
            {
                return this.endorserPartyField;
            }
            set
            {
                this.endorserPartyField = value;
            }
        }
        
        /// <summary>
        ///  Details of the application of a Certificate of Origin.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public CertificateOfOriginApplicationType CertificateOfOriginApplication
        {
            get
            {
                return this.certificateOfOriginApplicationField;
            }
            set
            {
                this.certificateOfOriginApplicationField = value;
            }
        }
        
        /// <summary>
        ///  Issuer Endorsement details.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public EndorsementType IssuerEndorsement
        {
            get
            {
                return this.issuerEndorsementField;
            }
            set
            {
                this.issuerEndorsementField = value;
            }
        }
        
        /// <summary>
        ///  Embassy Endorsement details.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public EndorsementType EmbassyEndorsement
        {
            get
            {
                return this.embassyEndorsementField;
            }
            set
            {
                this.embassyEndorsementField = value;
            }
        }
        
        /// <summary>
        ///  Insurance Endorsement details.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public EndorsementType InsuranceEndorsement
        {
            get
            {
                return this.insuranceEndorsementField;
            }
            set
            {
                this.insuranceEndorsementField = value;
            }
        }
    }
}
