// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     http://ubllarsen.codeplex.com/
//
// </auto-generated>
//------------------------------------------------------------------------------
namespace UblLarsen.Ubl2
{
    using UblLarsen.Ubl2.Cac;
    
    
    /// <summary>
    ///  The document used to remind the customer of payments overdue.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("ublxsd", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:Reminder-2")]
    [System.Xml.Serialization.XmlRootAttribute("Reminder", Namespace="urn:oasis:names:specification:ubl:schema:xsd:Reminder-2", IsNullable=false)]
    public partial class ReminderType : UblBaseDocumentType
    {
        
        private Udt.IdentifierType idField;
        
        private Udt.IndicatorType copyIndicatorField;
        
        private Udt.IdentifierType uUIDField;
        
        private Udt.DateType issueDateField;
        
        private Udt.TimeType issueTimeField;
        
        private Udt.CodeType reminderTypeCodeField;
        
        private Udt.NumericType reminderSequenceNumericField;
        
        private Udt.TextType[] noteField;
        
        private Udt.DateType taxPointDateField;
        
        private Qdt.CurrencyCodeType documentCurrencyCodeField;
        
        private Qdt.CurrencyCodeType taxCurrencyCodeField;
        
        private Qdt.CurrencyCodeType pricingCurrencyCodeField;
        
        private Qdt.CurrencyCodeType paymentCurrencyCodeField;
        
        private Qdt.CurrencyCodeType paymentAlternativeCurrencyCodeField;
        
        private Udt.CodeType accountingCostCodeField;
        
        private Udt.TextType accountingCostField;
        
        private Udt.NumericType lineCountNumericField;
        
        private PeriodType[] reminderPeriodField;
        
        private DocumentReferenceType[] additionalDocumentReferenceField;
        
        private SignatureType[] signatureField;
        
        private SupplierPartyType accountingSupplierPartyField;
        
        private CustomerPartyType accountingCustomerPartyField;
        
        private PartyType payeePartyField;
        
        private PartyType taxRepresentativePartyField;
        
        private PaymentMeansType[] paymentMeansField;
        
        private PaymentTermsType[] paymentTermsField;
        
        private PaymentType[] prepaidPaymentField;
        
        private AllowanceChargeType[] allowanceChargeField;
        
        private ExchangeRateType taxExchangeRateField;
        
        private ExchangeRateType pricingExchangeRateField;
        
        private ExchangeRateType paymentExchangeRateField;
        
        private ExchangeRateType paymentAlternativeExchangeRateField;
        
        private TaxTotalType[] taxTotalField;
        
        private MonetaryTotalType legalMonetaryTotalField;
        
        private ReminderLineType[] reminderLineField;
        
        /// <summary>
        ///  An identifier for the Reminder assigned by the Creditor.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.IdentifierType ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <summary>
        ///  Indicates whether a document is a copy (true) or not (false).
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.IndicatorType CopyIndicator
        {
            get
            {
                return this.copyIndicatorField;
            }
            set
            {
                this.copyIndicatorField = value;
            }
        }
        
        /// <summary>
        ///  A universally unique identifier for an instance of this ABIE.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.IdentifierType UUID
        {
            get
            {
                return this.uUIDField;
            }
            set
            {
                this.uUIDField = value;
            }
        }
        
        /// <summary>
        ///  The date assigned by the Creditor on which the Invoice was issued.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.DateType IssueDate
        {
            get
            {
                return this.issueDateField;
            }
            set
            {
                this.issueDateField = value;
            }
        }
        
        /// <summary>
        ///  The time assigned by the Creditor on which the Reminder was issued.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.TimeType IssueTime
        {
            get
            {
                return this.issueTimeField;
            }
            set
            {
                this.issueTimeField = value;
            }
        }
        
        /// <summary>
        ///  Code specifying the type of the Reminder.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.CodeType ReminderTypeCode
        {
            get
            {
                return this.reminderTypeCodeField;
            }
            set
            {
                this.reminderTypeCodeField = value;
            }
        }
        
        /// <summary>
        ///  The sequence number of the current reminder. Specifies the number of reminders previously sent plus one.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.NumericType ReminderSequenceNumeric
        {
            get
            {
                return this.reminderSequenceNumericField;
            }
            set
            {
                this.reminderSequenceNumericField = value;
            }
        }
        
        /// <summary>
        ///  Free-form text applying to the Reminder. This element may contain notes or any other similar information that is not contained explicitly in another structure.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Note", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.TextType[] Note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }
        
        /// <summary>
        ///  The date of the Reminder used to indicate the point at which tax becomes applicable.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.DateType TaxPointDate
        {
            get
            {
                return this.taxPointDateField;
            }
            set
            {
                this.taxPointDateField = value;
            }
        }
        
        /// <summary>
        ///  The currency in which the Document is presented. This may be the same currency as the pricing or as the tax.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Qdt.CurrencyCodeType DocumentCurrencyCode
        {
            get
            {
                return this.documentCurrencyCodeField;
            }
            set
            {
                this.documentCurrencyCodeField = value;
            }
        }
        
        /// <summary>
        ///  The currency used for tax amounts in the Reminder.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Qdt.CurrencyCodeType TaxCurrencyCode
        {
            get
            {
                return this.taxCurrencyCodeField;
            }
            set
            {
                this.taxCurrencyCodeField = value;
            }
        }
        
        /// <summary>
        ///  The currency used for prices in the Reminder.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Qdt.CurrencyCodeType PricingCurrencyCode
        {
            get
            {
                return this.pricingCurrencyCodeField;
            }
            set
            {
                this.pricingCurrencyCodeField = value;
            }
        }
        
        /// <summary>
        ///  The currency used for payment in the Reminder.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Qdt.CurrencyCodeType PaymentCurrencyCode
        {
            get
            {
                return this.paymentCurrencyCodeField;
            }
            set
            {
                this.paymentCurrencyCodeField = value;
            }
        }
        
        /// <summary>
        ///  The alternative currency used for payment in the Reminder.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Qdt.CurrencyCodeType PaymentAlternativeCurrencyCode
        {
            get
            {
                return this.paymentAlternativeCurrencyCodeField;
            }
            set
            {
                this.paymentAlternativeCurrencyCodeField = value;
            }
        }
        
        /// <summary>
        ///  The Buyer's accounting code applied to the Reminder as a whole.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.CodeType AccountingCostCode
        {
            get
            {
                return this.accountingCostCodeField;
            }
            set
            {
                this.accountingCostCodeField = value;
            }
        }
        
        /// <summary>
        ///  The Buyer's accounting code applied to the Reminder as a whole, expressed as text.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.TextType AccountingCost
        {
            get
            {
                return this.accountingCostField;
            }
            set
            {
                this.accountingCostField = value;
            }
        }
        
        /// <summary>
        ///  The number of lines in the document.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.NumericType LineCountNumeric
        {
            get
            {
                return this.lineCountNumericField;
            }
            set
            {
                this.lineCountNumericField = value;
            }
        }
        
        /// <summary>
        ///  An association to period(s) to which the Reminder applies.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ReminderPeriod", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public PeriodType[] ReminderPeriod
        {
            get
            {
                return this.reminderPeriodField;
            }
            set
            {
                this.reminderPeriodField = value;
            }
        }
        
        /// <summary>
        ///  An associative reference to Additional Document.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalDocumentReference", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public DocumentReferenceType[] AdditionalDocumentReference
        {
            get
            {
                return this.additionalDocumentReferenceField;
            }
            set
            {
                this.additionalDocumentReferenceField = value;
            }
        }
        
        /// <summary>
        ///  An association to Signature.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Signature", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public SignatureType[] Signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }
        
        /// <summary>
        ///  An association to the Accounting Supplier Party.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public SupplierPartyType AccountingSupplierParty
        {
            get
            {
                return this.accountingSupplierPartyField;
            }
            set
            {
                this.accountingSupplierPartyField = value;
            }
        }
        
        /// <summary>
        ///  An association to the Accounting Customer Party.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public CustomerPartyType AccountingCustomerParty
        {
            get
            {
                return this.accountingCustomerPartyField;
            }
            set
            {
                this.accountingCustomerPartyField = value;
            }
        }
        
        /// <summary>
        ///  An association to the Payee.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public PartyType PayeeParty
        {
            get
            {
                return this.payeePartyField;
            }
            set
            {
                this.payeePartyField = value;
            }
        }
        
        /// <summary>
        ///  An association to the Tax Representative.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public PartyType TaxRepresentativeParty
        {
            get
            {
                return this.taxRepresentativePartyField;
            }
            set
            {
                this.taxRepresentativePartyField = value;
            }
        }
        
        /// <summary>
        ///  An association to Payment Means.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("PaymentMeans", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public PaymentMeansType[] PaymentMeans
        {
            get
            {
                return this.paymentMeansField;
            }
            set
            {
                this.paymentMeansField = value;
            }
        }
        
        /// <summary>
        ///  An association to Payment Terms.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("PaymentTerms", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public PaymentTermsType[] PaymentTerms
        {
            get
            {
                return this.paymentTermsField;
            }
            set
            {
                this.paymentTermsField = value;
            }
        }
        
        /// <summary>
        ///  An association to prepaid payment(s).
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("PrepaidPayment", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public PaymentType[] PrepaidPayment
        {
            get
            {
                return this.prepaidPaymentField;
            }
            set
            {
                this.prepaidPaymentField = value;
            }
        }
        
        /// <summary>
        ///  An association to Allowances and Charges that apply to the Reminder as a whole.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("AllowanceCharge", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public AllowanceChargeType[] AllowanceCharge
        {
            get
            {
                return this.allowanceChargeField;
            }
            set
            {
                this.allowanceChargeField = value;
            }
        }
        
        /// <summary>
        ///  An association to Exchange Rate between the Document Currency and the Tax Currency.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ExchangeRateType TaxExchangeRate
        {
            get
            {
                return this.taxExchangeRateField;
            }
            set
            {
                this.taxExchangeRateField = value;
            }
        }
        
        /// <summary>
        ///  An association to Exchange Rate between the Document Currency and the Pricing Currency.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ExchangeRateType PricingExchangeRate
        {
            get
            {
                return this.pricingExchangeRateField;
            }
            set
            {
                this.pricingExchangeRateField = value;
            }
        }
        
        /// <summary>
        ///  An association to Exchange Rate between the Document Currency and the Payment Currency.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ExchangeRateType PaymentExchangeRate
        {
            get
            {
                return this.paymentExchangeRateField;
            }
            set
            {
                this.paymentExchangeRateField = value;
            }
        }
        
        /// <summary>
        ///  An association to Exchange Rate between the Document Currency and the Payment Alternative Currency.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ExchangeRateType PaymentAlternativeExchangeRate
        {
            get
            {
                return this.paymentAlternativeExchangeRateField;
            }
            set
            {
                this.paymentAlternativeExchangeRateField = value;
            }
        }
        
        /// <summary>
        ///  An association to Tax Total for specific tax types/rates.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("TaxTotal", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public TaxTotalType[] TaxTotal
        {
            get
            {
                return this.taxTotalField;
            }
            set
            {
                this.taxTotalField = value;
            }
        }
        
        /// <summary>
        ///  An association to the total amount payable on the Invoice, including Allowances, Charges, and Taxes.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public MonetaryTotalType LegalMonetaryTotal
        {
            get
            {
                return this.legalMonetaryTotalField;
            }
            set
            {
                this.legalMonetaryTotalField = value;
            }
        }
        
        /// <summary>
        ///  An association to Reminder Line.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ReminderLine", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ReminderLineType[] ReminderLine
        {
            get
            {
                return this.reminderLineField;
            }
            set
            {
                this.reminderLineField = value;
            }
        }
    }
}
