// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     http://ubllarsen.codeplex.com/
//
// </auto-generated>
//------------------------------------------------------------------------------
namespace UblLarsen.Ubl2
{
    using UblLarsen.Ubl2.Cac;
    
    
    /// <summary>
    ///  The Bill of Lading is issued by the party who acts as an agent for the carrier or other agents to the party who gives instructions for the transportation services (shipper, consignor, etc.) stating the details of the transportation, charges, and terms and conditions under which the transportation service is provided. The party issuing this document does not necessarily provide the physical transportation service. It corresponds to the information on the Forwarding Instruction. It is used for any mode of transport.
    ///  A Bill of Lading can serve as a contractual document between the parties for the transportation service.  The document evidences a contract of carriage by sea and the acceptance of responsibility for the goods by the carrier, and by which the carrier undertakes to deliver the goods against surrender of the document.  A provision in the document that the goods are to be delivered to the order of a named person, or to order, or to bearer, constitutes such an undertaking.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("ublxsd", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:BillOfLading-2")]
    [System.Xml.Serialization.XmlRootAttribute("BillOfLading", Namespace="urn:oasis:names:specification:ubl:schema:xsd:BillOfLading-2", IsNullable=false)]
    public partial class BillOfLadingType : UblBaseDocumentType
    {
        
        private Udt.IdentifierType idField;
        
        private Udt.IdentifierType carrierAssignedIDField;
        
        private Udt.IdentifierType uUIDField;
        
        private Udt.DateType issueDateField;
        
        private Udt.TimeType issueTimeField;
        
        private Udt.NameType nameField;
        
        private Udt.TextType[] descriptionField;
        
        private Udt.TextType[] noteField;
        
        private Qdt.DocumentStatusCodeType documentStatusCodeField;
        
        private Udt.IdentifierType shippingOrderIDField;
        
        private Udt.IndicatorType toOrderIndicatorField;
        
        private Udt.IndicatorType adValoremIndicatorField;
        
        private Udt.AmountType declaredCarriageValueAmountField;
        
        private Udt.TextType[] otherInstructionField;
        
        private PartyType consignorPartyField;
        
        private PartyType carrierPartyField;
        
        private PartyType freightForwarderPartyField;
        
        private ShipmentType shipmentField;
        
        private DocumentReferenceType[] documentReferenceField;
        
        private ExchangeRateType[] exchangeRateField;
        
        private DocumentDistributionType[] documentDistributionField;
        
        private SignatureType[] signatureField;
        
        /// <summary>
        ///  Unique Identifier of the Bill Of Lading. Reference number to identify a document evidencing a transport contract.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.IdentifierType ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <summary>
        ///  Reference number assigned by a carrier or its agent to identify a specific shipment such as a booking reference number when cargo space is reserved prior to loading.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.IdentifierType CarrierAssignedID
        {
            get
            {
                return this.carrierAssignedIDField;
            }
            set
            {
                this.carrierAssignedIDField = value;
            }
        }
        
        /// <summary>
        ///  A universally unique identifier for an instance of this ABIE.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.IdentifierType UUID
        {
            get
            {
                return this.uUIDField;
            }
            set
            {
                this.uUIDField = value;
            }
        }
        
        /// <summary>
        ///  Date on which the Bill Of Lading was issued.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.DateType IssueDate
        {
            get
            {
                return this.issueDateField;
            }
            set
            {
                this.issueDateField = value;
            }
        }
        
        /// <summary>
        ///  Time at which the Bill Of Lading was issued.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.TimeType IssueTime
        {
            get
            {
                return this.issueTimeField;
            }
            set
            {
                this.issueTimeField = value;
            }
        }
        
        /// <summary>
        ///  The business name given to the document type.
        ///  Example: "House Bill", "Consolidated Bill of Lading", "Proforma", "Sea Waybill"
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.NameType Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <summary>
        ///  Textual description of the document instance.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Description", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.TextType[] Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <summary>
        ///  Contains any free-form text pertinent to the entire document or to the document message itself. This element may contain notes or any other similar information that is not contained explicitly in another structure.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Note", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.TextType[] Note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }
        
        /// <summary>
        ///  Indicates the status of the Bill Of Lading (revision, replacement, etc.).
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Qdt.DocumentStatusCodeType DocumentStatusCode
        {
            get
            {
                return this.documentStatusCodeField;
            }
            set
            {
                this.documentStatusCodeField = value;
            }
        }
        
        /// <summary>
        ///  Reference number to identify a Shipping Order or Forwarding Instruction.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.IdentifierType ShippingOrderID
        {
            get
            {
                return this.shippingOrderIDField;
            }
            set
            {
                this.shippingOrderIDField = value;
            }
        }
        
        /// <summary>
        ///  Indicates whether the transport document is consigned to order.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.IndicatorType ToOrderIndicator
        {
            get
            {
                return this.toOrderIndicatorField;
            }
            set
            {
                this.toOrderIndicatorField = value;
            }
        }
        
        /// <summary>
        ///  A term used in commerce in reference to certain duties, called ad valorem duties, which are levied on commodities at certain rates per centum on their value.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.IndicatorType AdValoremIndicator
        {
            get
            {
                return this.adValoremIndicatorField;
            }
            set
            {
                this.adValoremIndicatorField = value;
            }
        }
        
        /// <summary>
        ///  Value, declared by the shipper or his agent solely for the purpose of varying the carrier's level of liability from that provided in the contract of carriage, in case of loss or damage to goods or delayed delivery.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.AmountType DeclaredCarriageValueAmount
        {
            get
            {
                return this.declaredCarriageValueAmountField;
            }
            set
            {
                this.declaredCarriageValueAmountField = value;
            }
        }
        
        /// <summary>
        ///  Contains other free-text-based instructions related to the shipment to the forwarders or carriers. This should only be used where such information cannot be represented in other structured information entities within the document.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OtherInstruction", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.TextType[] OtherInstruction
        {
            get
            {
                return this.otherInstructionField;
            }
            set
            {
                this.otherInstructionField = value;
            }
        }
        
        /// <summary>
        ///  The party consigning goods as stipulated in the transport contract by the party ordering transport.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public PartyType ConsignorParty
        {
            get
            {
                return this.consignorPartyField;
            }
            set
            {
                this.consignorPartyField = value;
            }
        }
        
        /// <summary>
        ///  The party providing the transport of goods between named points.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public PartyType CarrierParty
        {
            get
            {
                return this.carrierPartyField;
            }
            set
            {
                this.carrierPartyField = value;
            }
        }
        
        /// <summary>
        ///  The party combining individual smaller consignments into a single larger shipment (so called consolidated shipment) that is sent to a counterpart who mirrors the consolidator's activity by dividing the consolidated consignment into its original components.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public PartyType FreightForwarderParty
        {
            get
            {
                return this.freightForwarderPartyField;
            }
            set
            {
                this.freightForwarderPartyField = value;
            }
        }
        
        /// <summary>
        ///  An association to Shipment.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ShipmentType Shipment
        {
            get
            {
                return this.shipmentField;
            }
            set
            {
                this.shipmentField = value;
            }
        }
        
        /// <summary>
        ///  An association to Document Reference.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("DocumentReference", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public DocumentReferenceType[] DocumentReference
        {
            get
            {
                return this.documentReferenceField;
            }
            set
            {
                this.documentReferenceField = value;
            }
        }
        
        /// <summary>
        ///  Information that directly relates to the rate of exchange (conversion) between two currencies.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ExchangeRate", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ExchangeRateType[] ExchangeRate
        {
            get
            {
                return this.exchangeRateField;
            }
            set
            {
                this.exchangeRateField = value;
            }
        }
        
        /// <summary>
        ///  The distribution of the Bill of Lading to interested parties.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("DocumentDistribution", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public DocumentDistributionType[] DocumentDistribution
        {
            get
            {
                return this.documentDistributionField;
            }
            set
            {
                this.documentDistributionField = value;
            }
        }
        
        /// <summary>
        ///  One or more signatures applied to the document instance.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Signature", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public SignatureType[] Signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }
    }
}
