// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     http://ubllarsen.codeplex.com/
//
// </auto-generated>
//------------------------------------------------------------------------------
namespace UblLarsen.Ubl2
{
    using UblLarsen.Ubl2.Cac;
    
    
    /// <summary>
    ///  The document used to request a Catalogue.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("ublxsd", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CatalogueRequest-2")]
    [System.Xml.Serialization.XmlRootAttribute("CatalogueRequest", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CatalogueRequest-2", IsNullable=false)]
    public partial class CatalogueRequestType : UblBaseDocumentType
    {
        
        private Udt.IdentifierType idField;
        
        private Udt.IdentifierType uUIDField;
        
        private Udt.NameType nameField;
        
        private Udt.DateType issueDateField;
        
        private Udt.TimeType issueTimeField;
        
        private Udt.TextType[] noteField;
        
        private Udt.TextType[] descriptionField;
        
        private Udt.IndicatorType pricingUpdateRequestIndicatorField;
        
        private Udt.IndicatorType itemUpdateRequestIndicatorField;
        
        private Udt.NumericType lineCountNumericField;
        
        private PeriodType[] validityPeriodField;
        
        private PartyType receiverPartyField;
        
        private PartyType providerPartyField;
        
        private SupplierPartyType sellerSupplierPartyField;
        
        private CustomerPartyType contractorCustomerPartyField;
        
        private CatalogueReferenceType requestedCatalogueReferenceField;
        
        private ContractType[] referencedContractField;
        
        private TradingTermsType tradingTermsField;
        
        private DocumentReferenceType[] documentReferenceField;
        
        private AddressType[] applicableTerritoryAddressField;
        
        private LanguageType requestedLanguageField;
        
        private ClassificationSchemeType[] requestedClassificationSchemeField;
        
        private CatalogueRequestLineType[] catalogueRequestLineField;
        
        /// <summary>
        ///  An identifier for the Catalogue Request assigned by the party managing the catalogue (either the Catalogue Requesting Party or the Catalogue Providing Party).
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.IdentifierType ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <summary>
        ///  A universally unique identifier for an instance of this ABIE.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.IdentifierType UUID
        {
            get
            {
                return this.uUIDField;
            }
            set
            {
                this.uUIDField = value;
            }
        }
        
        /// <summary>
        ///  A name given to the Catalogue Request.
        ///  Example: "winter 2005 collection"
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.NameType Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <summary>
        ///  The date assigned by the Catalogue Managing Party on which the Catalogue was requested.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.DateType IssueDate
        {
            get
            {
                return this.issueDateField;
            }
            set
            {
                this.issueDateField = value;
            }
        }
        
        /// <summary>
        ///  The time assigned by the Catalogue Managing Party at which the Catalogue was requested.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.TimeType IssueTime
        {
            get
            {
                return this.issueTimeField;
            }
            set
            {
                this.issueTimeField = value;
            }
        }
        
        /// <summary>
        ///  Free-form text applying to the Catalogue Request. This element may contain notes or any other similar information that is not contained explicitly in another structure.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Note", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.TextType[] Note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }
        
        /// <summary>
        ///  Textual description of the document instance.
        ///  Example: "latest computer accessories for laptops"
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Description", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.TextType[] Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <summary>
        ///  The indicator requesting a pricing update.
        ///  Example: default is true
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.IndicatorType PricingUpdateRequestIndicator
        {
            get
            {
                return this.pricingUpdateRequestIndicatorField;
            }
            set
            {
                this.pricingUpdateRequestIndicatorField = value;
            }
        }
        
        /// <summary>
        ///  The indicator requesting an update of the item specifications.
        ///  Example: default is true
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.IndicatorType ItemUpdateRequestIndicator
        {
            get
            {
                return this.itemUpdateRequestIndicatorField;
            }
            set
            {
                this.itemUpdateRequestIndicatorField = value;
            }
        }
        
        /// <summary>
        ///  The number of lines in the document.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Udt.NumericType LineCountNumeric
        {
            get
            {
                return this.lineCountNumericField;
            }
            set
            {
                this.lineCountNumericField = value;
            }
        }
        
        /// <summary>
        ///  The period assigned by the Catalogue Managing Party during which the information in the Catalogue requested is to be effective.  This may be given as start and end dates or a duration.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ValidityPeriod", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public PeriodType[] ValidityPeriod
        {
            get
            {
                return this.validityPeriodField;
            }
            set
            {
                this.validityPeriodField = value;
            }
        }
        
        /// <summary>
        ///  An association to the Catalogue Receiver Party.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public PartyType ReceiverParty
        {
            get
            {
                return this.receiverPartyField;
            }
            set
            {
                this.receiverPartyField = value;
            }
        }
        
        /// <summary>
        ///  An association to the Catalogue Provider Party.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public PartyType ProviderParty
        {
            get
            {
                return this.providerPartyField;
            }
            set
            {
                this.providerPartyField = value;
            }
        }
        
        /// <summary>
        ///  The Supplier Party responsible for the contract to which the Catalogue relates.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public SupplierPartyType SellerSupplierParty
        {
            get
            {
                return this.sellerSupplierPartyField;
            }
            set
            {
                this.sellerSupplierPartyField = value;
            }
        }
        
        /// <summary>
        ///  The Customer Party responsible for the contract to which the Catalogue relates.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public CustomerPartyType ContractorCustomerParty
        {
            get
            {
                return this.contractorCustomerPartyField;
            }
            set
            {
                this.contractorCustomerPartyField = value;
            }
        }
        
        /// <summary>
        ///  An association to a specific Catalogue; used if the Catalogue Request is for an update.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public CatalogueReferenceType RequestedCatalogueReference
        {
            get
            {
                return this.requestedCatalogueReferenceField;
            }
            set
            {
                this.requestedCatalogueReferenceField = value;
            }
        }
        
        /// <summary>
        ///  An association to a framework agreement or contract.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ReferencedContract", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ContractType[] ReferencedContract
        {
            get
            {
                return this.referencedContractField;
            }
            set
            {
                this.referencedContractField = value;
            }
        }
        
        /// <summary>
        ///  An association to trading terms.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public TradingTermsType TradingTerms
        {
            get
            {
                return this.tradingTermsField;
            }
            set
            {
                this.tradingTermsField = value;
            }
        }
        
        /// <summary>
        ///  An association to other documents.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("DocumentReference", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public DocumentReferenceType[] DocumentReference
        {
            get
            {
                return this.documentReferenceField;
            }
            set
            {
                this.documentReferenceField = value;
            }
        }
        
        /// <summary>
        ///  An association to the territory (regions, country, city, etc.) to which the requested Catalogue will apply.  Expressed as an Address.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ApplicableTerritoryAddress", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public AddressType[] ApplicableTerritoryAddress
        {
            get
            {
                return this.applicableTerritoryAddressField;
            }
            set
            {
                this.applicableTerritoryAddressField = value;
            }
        }
        
        /// <summary>
        ///  The language in which the Catalogue is requested to be provided.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public LanguageType RequestedLanguage
        {
            get
            {
                return this.requestedLanguageField;
            }
            set
            {
                this.requestedLanguageField = value;
            }
        }
        
        /// <summary>
        ///  An association to classification categories for the Catalogue requested.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("RequestedClassificationScheme", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ClassificationSchemeType[] RequestedClassificationScheme
        {
            get
            {
                return this.requestedClassificationSchemeField;
            }
            set
            {
                this.requestedClassificationSchemeField = value;
            }
        }
        
        /// <summary>
        ///  An association to specific Catalogue Lines for the catalogue requested.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("CatalogueRequestLine", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public CatalogueRequestLineType[] CatalogueRequestLine
        {
            get
            {
                return this.catalogueRequestLineField;
            }
            set
            {
                this.catalogueRequestLineField = value;
            }
        }
    }
}
